#!/bin/sh
for f in ~/dotfiles/*
do
    bn="$(basename "$f")"
    case "$bn" in
        INSTALL ) bn="";; # This installer.
        bashrc ) [ "$(uname)" = "Linux" ] && bn="bash_aliases";;
    esac
    [ "$bn" != "" ] && ln -fs "$f" "$HOME/.$bn"
done
