#!/bin/sh

[ "$(uname)" = "Darwin" ] && ln="/bin/ln -fhs" || ln="/bin/ln -fns"

for f in ~/dotfiles/*
do
    bn="$(basename "$f")"
    case "$bn" in
        INSTALL ) bn="";; # This installer.
        README.md ) bn="";; # README
        bashrc ) [ "$(uname)" = "Linux" ] && bn="bash_aliases";;
    esac
    [ "$bn" != "" ] && $ln "$f" "$HOME/.$bn"
done
